language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-7', 'g++-7']
      env: OCXX=g++-7 OCC=gcc-7 COMPILER=g++-7 IN_TRAVIS=true

before_install:
  - export CXX=$OCXX CC=$OCC
  - export project_root="$(pwd)"
  - export build_root="${project_root}-build"
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - $project_root/.travis/system_info

before_script:
  - $project_root/.travis/install_cmake
  - $project_root/.travis/install_3rd_party

script:
  - $project_root/.travis/var_info
  - $project_root/.travis/build

after_success:
  - $project_root/.travis/test
