language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: COMPILER=g++-7


before_install:
    - cat /etc/apt/sources.list
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.sh; chmod +x cmake-3.9.5-Linux-x86_64.sh
    - ./cmake-3.9.5-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

## configure step
before_script:
    - cd external_libs && ./init_libs && cd ..
    - ./build --travis --examples --testing -DCMAKE_CXX_COMPILER=$COMPILER

script:
  - cd ../libobi-build/release
  - make -j$(nproc)
  - make test
