language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','george-edison55-precise-backports']
          packages: ['g++-5', 'cmake-data', 'cmake']
      env: COMPILER=/usr/bin/g++-6 CXXSTD=c++1z

before_script:
    - cd ..
    - mkdir build
    - cd build
    - cmake -DCMAKE_TESTING=ON -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_FLAGS=-std=$CXXSTD ../libobi

script:
    - make -j$(nproc)
    - make test
