language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-7', 'g++-7']
      env: OCXX=g++-7 OCC=gcc-7 COMPILER=g++-7 IN_TRAVIS=true

before_install:
  - export CXX=$OCXX CC=$OCC
  - export build_type=release
  - export project_root="$(pwd)"
  - export build_base="${project_root}-build"
  - export build_root="${build_base}/$build_type"
  - export install_root="$HOME/usr"
  - export PATH="$install_root/bin:$PATH"
  - export build_prefix='<>'
  - $project_root/.build_scripts/system_info
  - $project_root/.build_scripts/var_info

before_script:
  - mkdir "$install_root"
  - mkdir -p "$build_root"
  - ln -s "$build_root" "$build_base/current"
  - $project_root/.build_scripts/install_cmake
  - $project_root/.build_scripts/install_3rd_party

script:
  - $project_root/.build_scripts/configure -DCMAKE_TESTING=ON -DLIBOBI_EXAMPLES=ON
  - $project_root/.build_scripts/build

after_success:
  - $project_root/.build_scripts/test
